name: Run Go & Python Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: payments_db
        ports:
          - 5432:5432
      rabbit:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ──────────────────────────────────────────────────────────────────────────────
      # Your existing Go setup & tests
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install Go dependencies
        run: go mod download
        working-directory: backend-services/inventory_go

      - name: Run Go tests
        run: go test ./... -v
        working-directory: backend-services/inventory_go
      # ──────────────────────────────────────────────────────────────────────────────

      # ──────────────────────────────────────────────────────────────────────────────
      # NEW: Python / FastAPI integration tests
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        working-directory: backend-services/payment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Start payment services (uses Docker Compose V2)
      - name: Start payment services
        working-directory: backend-services/payment
        run: |
          docker compose up -d
          # Give DB & RabbitMQ a few seconds to become ready
          sleep 15

      - name: Run Python integration tests
        working-directory: backend-services/payment
        run: pytest tests/integration.py -q

      - name: Tear down payment services
        if: always()
        working-directory: backend-services/payment
        run: docker compose down
      # ──────────────────────────────────────────────────────────────────────────────
